# Change these first
owner: upptime # Your GitHub organization or username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: EZcheats RU Site
    url: https://ezcheats.ru
  - name: EZcheats EN Site
    url: https://ezcheats.com
  - name: EZcheats Forum
    url: https://forum.ezcheats.ru
  - name: EZcheats Beta
    url: https://beta.ezcheats.com

status-website:
  baseUrl: /upptime
  name: EZcheats Status Website

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
