# Change these first
owner: ezcheatsofficial # Your GitHub organization or username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: EZcheats RU Site
    url: https://ezcheats.ru
  - name: EZcheats EN Site
    url: https://ezcheats.com
  - name: EZcheats Forum
    url: https://forum.ezcheats.ru
  - name: EZcheats Beta
    url: https://beta.ezcheats.com
  - name: EZcheats Cloud
    url: https://ezcheatscloud.com

assignees: # Users to assign downtime issues
  - 0niel
  - ramjke
  
status-website:
  baseUrl: /upptime
  name: EZcheats Status Website
  logoUrl: https://raw.githubusercontent.com/ezcheatsofficial/upptime/master/assets/logo.svg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ezcheatsofficial/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
